import { auditActorLabel, auditChangedFields } from "@/domain/audit-log/model";
import type { AuditEvent } from "@/domain/audit-log/types";
import type { Json } from "@/types/database";

// Only operational fields are projected into the interactive admin table.
const safeFields = new Set([
  "status", "state", "isPublic", "is_public", "name", "code", "reference", "timezone", "public_description",
  "arrival_date", "departure_date", "eta", "etd", "checked_in_at", "checked_out_at", "cancelled_at",
  "starts_at", "ends_at", "ended_reason", "currency", "model", "taxBehavior", "taxRateBps",
  "tax_behavior", "tax_rate_bps", "price_total_minor", "previous_price_total_minor", "amount_minor",
  "paid_minor", "refunded_minor", "balance_minor", "length_m", "beam_m", "draft_m", "max_length_m",
  "max_beam_m", "max_draft_m", "meterRateMinor", "meter_rate_minor", "startsOn", "endsOn",
  "seasons", "fees", "lengthRates", "minLengthM", "maxLengthM", "rateMinor", "amountMinor",
  "type", "kind", "rules", "hoursBeforeArrival", "refundPercent", "policy_code", "version",
  "public_description_local", "local_language", "contact_email", "contact_phone", "website_url",
  "evaluationRule", "tiers", "policyCode", "minDaysBeforeArrival", "maxDaysBeforeArrival",
  "nightlyRateMinor", "percentageBps",
]);

export function safeAuditText(value: string) {
  return value
    .replace(/\bPOSTMARK_API_TEST\b/g, "[redacted]")
    .replace(/\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/gi, "[redacted]")
    .replace(/\b(?:(?:sk|rk|pk)_(?:test|live)_|whsec_|acct_)[A-Za-z0-9_-]+\b/g, "[redacted]")
    .replace(/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g, "[redacted]")
    .replace(/\b(?:[A-Za-z0-9_]*(?:secret|token|password|credential|api_key)[A-Za-z0-9_]*)\s*[:=]\s*\S+/gi, "[redacted]");
}

function object(value: Json | null): Record<string, Json | undefined> {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function safeValue(value: Json | undefined): string | null {
  if (value === undefined) return null;
  if (value === null) return "Not set";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "string") return safeAuditText(value);
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map(safeValue).filter(Boolean).join("; ") || null;
  return Object.entries(value).filter(([key]) => safeFields.has(key)).map(([key, entry]) => {
    const text = safeValue(entry);
    return text === null ? null : `${humanize(key)}: ${text}`;
  }).filter(Boolean).join(" · ") || null;
}

export function humanize(value: string) {
  const text = value.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[_.]/g, " ");
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export type AuditTableEvent = {
  time: string; actor: string; actorType: AuditEvent["actor_type"]; action: string; entity: string;
  summary: string; source: string | null; changes: { field: string; before: string | null; after: string | null }[];
};

export function toAuditTableEvent(event: AuditEvent): AuditTableEvent {
  const before = object(event.before_data);
  const after = object(event.after_data);
  const fields = event.before_data && event.after_data ? auditChangedFields(event.before_data, event.after_data) : Object.keys(event.after_data ? after : before);
  const metadata = object(event.metadata);
  const entity = ["marina.published", "marina.unpublished"].includes(event.event_type) ? "Public Booking Page" : humanize(event.entity_type);
  const reference = after.reference ?? before.reference ?? after.code ?? before.code;
  // These metadata fields are generated by existing audit triggers, not inferred actors.
  const source = [metadata.source_table, metadata.source_function, metadata.operation, metadata.evaluation_rule]
    .filter((value): value is string => typeof value === "string").map((value) => safeAuditText(humanize(value))).join(" · ");
  return {
    time: event.occurred_at, actor: safeAuditText(auditActorLabel(event.actor_type, event.actor_email)), actorType: event.actor_type,
    action: safeAuditText(humanize(event.event_type)), entity: `${entity}${typeof reference === "string" ? ` · ${safeAuditText(reference)}` : ""}`,
    summary: safeAuditText(event.summary), source: source || null,
    changes: fields.filter((field) => safeFields.has(field)).map((field) => ({ field: humanize(field), before: safeValue(before[field]), after: safeValue(after[field]) }))
      .filter((change) => change.before !== null || change.after !== null),
  };
}

export function auditDate(value: string, timezone: string) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(value));
  return ["year", "month", "day"].map((type) => parts.find((part) => part.type === type)?.value).join("-");
}

export function filterAuditEvents(events: AuditTableEvent[], filters: { search: string; actor: string; action: string; from: string; to: string }, timezone: string) {
  const search = filters.search.trim().toLowerCase();
  return events.filter((event) => {
    const date = auditDate(event.time, timezone);
    return (!search || [event.actor, event.action, event.entity, event.summary].join(" ").toLowerCase().includes(search))
      && (!filters.actor || event.actor === filters.actor) && (!filters.action || event.action === filters.action)
      && (!filters.from || date >= filters.from) && (!filters.to || date <= filters.to);
  });
}
